### ISSUE TITLE
Atom Mac: autocomplete Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by phaseRazor** [peter-b/atom-language-livecode#36]
I'm having a autocomplete error after typing 3 letters while using .livecode files. Everything seems to work. I just get a wall of error messages every time I type anything. Other then that, it's pretty great. Is there anything I can do to stop these messages?

## Stack Trace for error.

/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:228
Hide Stack Trace
TypeError: Cannot read property 'toLowerCase' of undefined
    at SymbolStore.fuzzyMatchScore (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:228:68)
    at SymbolStore.scoreSymbol (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:214:27)
    at SymbolStore.symbolsForConfig (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:91:41)
    at SymbolProvider.getSuggestions (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:364:47)
    at providers.forEach.provider (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/Users/myName/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)

**Comment by phaseRazor** [comment]
Update of atom seems to have fixed the issue. It's working fine now.
